$axure.loadCurrentPage({
  "url":"场景.html",
  "generationDate":new Date(1450147155078.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"144fb57f9c1f42fab0a2a7d85ee9fb90",
    "type":"Axure:Page",
    "name":"场景",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e487f88408574a329e8672271779371e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c88adaa058e149b0a77bd743d1f1d12f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"829b72984bcc4d37810c9191e747c546",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":370,
              "height":658}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5958fea8519e41a39643bd8a36403a20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":370,
                  "height":658}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/场景/u2.jpg"}},
{
          "id":"842b67a763c64ed785811713c637afd2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 统一控制-选择灯具",
                      "target":{
                        "targetType":"page",
                        "url":"统一控制-选择灯具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e9d11ec9373141a3a953ba229aa84b85",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":140},
            "size":{
              "width":50,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑",
                      "target":{
                        "targetType":"page",
                        "url":"编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"127f082acdd8456989cb635419844b88",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":714},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 灯具",
                      "target":{
                        "targetType":"page",
                        "url":"灯具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"13841cb6960c4bd4aefecc9d4e6a5f19",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":716},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 场景",
                      "target":{
                        "targetType":"page",
                        "url":"场景.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fe82cd220674458b9f563c028b6e3104",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":715},
            "size":{
              "width":114,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"938cbdda835c4b06a5602050e207c185",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":287,
              "y":206},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646610be3e1842878d0c74bd588a2a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":287,
                  "y":206},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"ac11f47202ea4d4a92c84385dab276f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":378,
              "y":144},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46e840e908ea429d9c927b281a3906af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":378,
                  "y":144},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"f895ddb10e984fc3a1ad1194f6b870cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":110,
              "y":718},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3510b04ca93426aad7430b29c0c06cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":110,
                  "y":718},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"5acf76d37a4640858d4ff9c1f628fe4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":240,
              "y":720},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d42eae521024d939c86ac6bdcdbd75a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":240,
                  "y":720},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"f4738900d0f94deda38065def77433c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":360,
              "y":720},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1e9839c7404899a607993078e2538e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":360,
                  "y":720},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e487f88408574a329e8672271779371e":{
      "scriptId":"u0"},
    "c88adaa058e149b0a77bd743d1f1d12f":{
      "scriptId":"u1"},
    "829b72984bcc4d37810c9191e747c546":{
      "scriptId":"u2"},
    "5958fea8519e41a39643bd8a36403a20":{
      "scriptId":"u3"},
    "842b67a763c64ed785811713c637afd2":{
      "scriptId":"u4"},
    "e9d11ec9373141a3a953ba229aa84b85":{
      "scriptId":"u5"},
    "127f082acdd8456989cb635419844b88":{
      "scriptId":"u6"},
    "13841cb6960c4bd4aefecc9d4e6a5f19":{
      "scriptId":"u7"},
    "fe82cd220674458b9f563c028b6e3104":{
      "scriptId":"u8"},
    "938cbdda835c4b06a5602050e207c185":{
      "scriptId":"u9"},
    "646610be3e1842878d0c74bd588a2a07":{
      "scriptId":"u10"},
    "ac11f47202ea4d4a92c84385dab276f8":{
      "scriptId":"u11"},
    "46e840e908ea429d9c927b281a3906af":{
      "scriptId":"u12"},
    "f895ddb10e984fc3a1ad1194f6b870cf":{
      "scriptId":"u13"},
    "e3510b04ca93426aad7430b29c0c06cb":{
      "scriptId":"u14"},
    "5acf76d37a4640858d4ff9c1f628fe4f":{
      "scriptId":"u15"},
    "0d42eae521024d939c86ac6bdcdbd75a":{
      "scriptId":"u16"},
    "f4738900d0f94deda38065def77433c8":{
      "scriptId":"u17"},
    "9d1e9839c7404899a607993078e2538e":{
      "scriptId":"u18"}}});