$axure.loadCurrentPage({
  "url":"无成功绑定设备.html",
  "generationDate":new Date(1450070652395.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e0cf61729960426e913a929dd306ce76",
    "type":"Axure:Page",
    "name":"无成功绑定设备",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ac219752f7e6473dbd6f0dce0bcdd64f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94e281a596bf4eea9fa00a6c15d3fa5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"ec63bc6d12d64defa03927d2cdd0cd3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":373,
              "height":666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241eb88976804f6aa30f884cf4bf5dfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":373,
                  "height":666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/无成功绑定设备/u2.jpg"}},
{
          "id":"e79cc9042a244532944dbed5ceb113af",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "ac219752f7e6473dbd6f0dce0bcdd64f":{
      "scriptId":"u0"},
    "94e281a596bf4eea9fa00a6c15d3fa5f":{
      "scriptId":"u1"},
    "ec63bc6d12d64defa03927d2cdd0cd3a":{
      "scriptId":"u2"},
    "241eb88976804f6aa30f884cf4bf5dfc":{
      "scriptId":"u3"},
    "e79cc9042a244532944dbed5ceb113af":{
      "scriptId":"u4"}}});