$axure.loadCurrentPage({
  "url":"颜色选择.html",
  "generationDate":new Date(1450147154963.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"972a159446684bcdbf73c2a636500722",
    "type":"Axure:Page",
    "name":"颜色选择",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4694d7a6555c44fbabbb1374dbdfb2fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4063de60dcb5452fa9fae0d53aaecfcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"7d21d73dd6554ae2931edaee6c2f9d1b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":112},
            "size":{
              "width":370,
              "height":658}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d47408f0ba4b93b363723129192353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":112},
                "size":{
                  "width":370,
                  "height":658}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色选择/u2.jpg"}},
{
          "id":"cce60ab527a64ad3b3e93a01f997f01c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4694d7a6555c44fbabbb1374dbdfb2fb":{
      "scriptId":"u0"},
    "4063de60dcb5452fa9fae0d53aaecfcc":{
      "scriptId":"u1"},
    "7d21d73dd6554ae2931edaee6c2f9d1b":{
      "scriptId":"u2"},
    "31d47408f0ba4b93b363723129192353":{
      "scriptId":"u3"},
    "cce60ab527a64ad3b3e93a01f997f01c":{
      "scriptId":"u4"}}});