$axure.loadCurrentPage({
  "url":"启动页.html",
  "generationDate":new Date(1437730018647.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f3f3ef9a59544c479bffad5523480084",
    "type":"Axure:Page",
    "name":"启动页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c0bececf094741129d51f92212ea5b50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49da5b3a8ed24e6fbcffd73f600d6c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"e2890d11b12345a2b58b7d3fe1bfd4d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":110},
            "size":{
              "width":370,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef6d9adf5b54a9491c44a6fe6d85500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":110},
                "size":{
                  "width":370,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 灯具",
                      "target":{
                        "targetType":"page",
                        "url":"灯具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动页/u2.png"}},
{
          "id":"6b75b75795d240f6811f9c6f7f125d41",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":166,
              "y":340},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"610780318eb64ef4b00f4b2967a88c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":166,
                  "y":340},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4782dada3c949c9959d61bf4c3c902d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":370,
              "height":658}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9296a119c39f42bea4805f00b87f3a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":370,
                  "height":658}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页/u6.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "c0bececf094741129d51f92212ea5b50":{
      "scriptId":"u0"},
    "49da5b3a8ed24e6fbcffd73f600d6c65":{
      "scriptId":"u1"},
    "e2890d11b12345a2b58b7d3fe1bfd4d7":{
      "scriptId":"u2"},
    "aef6d9adf5b54a9491c44a6fe6d85500":{
      "scriptId":"u3"},
    "6b75b75795d240f6811f9c6f7f125d41":{
      "scriptId":"u4"},
    "610780318eb64ef4b00f4b2967a88c75":{
      "scriptId":"u5"},
    "a4782dada3c949c9959d61bf4c3c902d":{
      "scriptId":"u6"},
    "9296a119c39f42bea4805f00b87f3a17":{
      "scriptId":"u7"}}});