$axure.loadCurrentPage({
  "url":"多孔插座更多控制.html",
  "generationDate":new Date(1450070652298.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"658cb3adf80a45b0b67b00dc321d56e4",
    "type":"Axure:Page",
    "name":"多孔插座更多控制",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2d665524761c44be9620fab663bc5d02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":605},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d07eb23439d449e884067160e9326a28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":605},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u0.png"}},
{
          "id":"b30d7fcf073d44658d2c21abc75df62c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":605},
            "size":{
              "width":430,
              "height":605},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45c7f4f1337429ba79b2497239a4700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":605},
                "size":{
                  "width":430,
                  "height":605},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u2.png"}},
{
          "id":"b19a3f40eb444045807aa5f3b6dc73d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1206},
            "size":{
              "width":430,
              "height":183},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb0539306ac4b23b2786784adde8748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1206},
                "size":{
                  "width":430,
                  "height":183},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u4.png"}},
{
          "id":"797c787054d443aea54ac221cf491dc6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":374,
              "height":1175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8f9d34bf7284b939c7a8275371c4958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":374,
                  "height":1175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/多孔插座更多控制/u6.jpg"}},
{
          "id":"b4f18499fd2c466e8f024e0a5447f78a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":620},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 多孔插座定时",
                      "target":{
                        "targetType":"page",
                        "url":"多孔插座定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"76926bab3c064501923e48b849bfd9ae",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"98d8f6a01ca448488303fec1d67f7739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":378,
              "y":632},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"799a9173054040be8b969893cd6e9a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":378,
                  "y":632},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"48014cab086343a6860af18aaf9059bd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":1030},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 倒计时设置",
                      "target":{
                        "targetType":"page",
                        "url":"倒计时设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e55006e8350e4d288d4681c3abf16c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":380,
              "y":1040},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe5b9c136b14e2b92156aed03000bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":380,
                  "y":1040},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2d665524761c44be9620fab663bc5d02":{
      "scriptId":"u0"},
    "d07eb23439d449e884067160e9326a28":{
      "scriptId":"u1"},
    "b30d7fcf073d44658d2c21abc75df62c":{
      "scriptId":"u2"},
    "b45c7f4f1337429ba79b2497239a4700":{
      "scriptId":"u3"},
    "b19a3f40eb444045807aa5f3b6dc73d2":{
      "scriptId":"u4"},
    "6fb0539306ac4b23b2786784adde8748":{
      "scriptId":"u5"},
    "797c787054d443aea54ac221cf491dc6":{
      "scriptId":"u6"},
    "e8f9d34bf7284b939c7a8275371c4958":{
      "scriptId":"u7"},
    "b4f18499fd2c466e8f024e0a5447f78a":{
      "scriptId":"u8"},
    "76926bab3c064501923e48b849bfd9ae":{
      "scriptId":"u9"},
    "98d8f6a01ca448488303fec1d67f7739":{
      "scriptId":"u10"},
    "799a9173054040be8b969893cd6e9a2d":{
      "scriptId":"u11"},
    "48014cab086343a6860af18aaf9059bd":{
      "scriptId":"u12"},
    "e55006e8350e4d288d4681c3abf16c4d":{
      "scriptId":"u13"},
    "4fe5b9c136b14e2b92156aed03000bf9":{
      "scriptId":"u14"}}});