$axure.loadCurrentPage({
  "url":"照明模式.html",
  "generationDate":new Date(1450070652050.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3c1ea04b64e64f1fa8660fc496f49b21",
    "type":"Axure:Page",
    "name":"照明模式",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f4f6510ce79e4e30bd5f00f12cc5f891",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":591},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d13f28c16ace4ed59e9fd989a47b3704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":591},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更多设置/u0.png"}},
{
          "id":"a25c0ef4767b4f4a83a9b40761342040",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":591},
            "size":{
              "width":430,
              "height":599},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69786b5572514dcca267df15d6dbc224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":591},
                "size":{
                  "width":430,
                  "height":599},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更多设置/u2.png"}},
{
          "id":"110d3a653a844671b0c8eb0e3f52def7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":430,
              "height":171},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b2419b9b2243609bdeb22ac80bb3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":430,
                  "height":171},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更多设置/u4.png"}},
{
          "id":"10dc56feefaa49d1bc3d45f2c676feba",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":910},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加定时",
                      "target":{
                        "targetType":"page",
                        "url":"添加定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"613195169aec4e3885e13c003cef5087",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":190},
            "size":{
              "width":181,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"347ca92565244242802c9b7c7f6cba8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":373,
              "height":1140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dd98c0cea854ac9ac1e85403a16de6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":373,
                  "height":1140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/照明模式/u8.jpg"}},
{
          "id":"38e38b1eb5b34f0b869b61eee90a940a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":180},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更多设置",
                      "target":{
                        "targetType":"page",
                        "url":"更多设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"839a406478034fc2a05b3350d67456e0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":560},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加定时",
                      "target":{
                        "targetType":"page",
                        "url":"添加定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb2b7962cc3944dda36a0c02018c445c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eee3f6dac7c4433399e05917ea9dee47",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":970},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 倒计时设置",
                      "target":{
                        "targetType":"page",
                        "url":"倒计时设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0ce13e17f0ff4584822dcabfbd56395b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":370,
              "y":566},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04836024f824cff9c9da77435f7a17d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":370,
                  "y":566},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"bfefde7ae3264aea97bee19f3fb04931",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":370,
              "y":976},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5f1f72f9604b86af33fbded3cc08b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":370,
                  "y":976},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f4f6510ce79e4e30bd5f00f12cc5f891":{
      "scriptId":"u0"},
    "d13f28c16ace4ed59e9fd989a47b3704":{
      "scriptId":"u1"},
    "a25c0ef4767b4f4a83a9b40761342040":{
      "scriptId":"u2"},
    "69786b5572514dcca267df15d6dbc224":{
      "scriptId":"u3"},
    "110d3a653a844671b0c8eb0e3f52def7":{
      "scriptId":"u4"},
    "d7b2419b9b2243609bdeb22ac80bb3d3":{
      "scriptId":"u5"},
    "10dc56feefaa49d1bc3d45f2c676feba":{
      "scriptId":"u6"},
    "613195169aec4e3885e13c003cef5087":{
      "scriptId":"u7"},
    "347ca92565244242802c9b7c7f6cba8a":{
      "scriptId":"u8"},
    "3dd98c0cea854ac9ac1e85403a16de6f":{
      "scriptId":"u9"},
    "38e38b1eb5b34f0b869b61eee90a940a":{
      "scriptId":"u10"},
    "839a406478034fc2a05b3350d67456e0":{
      "scriptId":"u11"},
    "eb2b7962cc3944dda36a0c02018c445c":{
      "scriptId":"u12"},
    "eee3f6dac7c4433399e05917ea9dee47":{
      "scriptId":"u13"},
    "0ce13e17f0ff4584822dcabfbd56395b":{
      "scriptId":"u14"},
    "d04836024f824cff9c9da77435f7a17d":{
      "scriptId":"u15"},
    "bfefde7ae3264aea97bee19f3fb04931":{
      "scriptId":"u16"},
    "1c5f1f72f9604b86af33fbded3cc08b3":{
      "scriptId":"u17"}}});