$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1450070651761.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6c1a4669aae24f53a830502a61b82f39",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"87080c42f9994f1f9fc5903adf7d6335",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b97cccc3001c45a1aa42f7abf2b83ae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"8d2eb3e3fd704a238e176afee162058a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":374,
              "height":666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4ea81b536240fe8b2d00c3a3056356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":374,
                  "height":666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.jpg"}},
{
          "id":"54c2b528f7964e81ad4408661ee733b8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":720},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设备（在线&amp;离线）",
                      "target":{
                        "targetType":"page",
                        "url":"我的设备（在线_离线）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"73a9c08306724c65b5dd70757c092b6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":177,
              "y":730},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30941627256d4b938d39def48a4f960f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":177,
                  "y":730},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "87080c42f9994f1f9fc5903adf7d6335":{
      "scriptId":"u0"},
    "b97cccc3001c45a1aa42f7abf2b83ae8":{
      "scriptId":"u1"},
    "8d2eb3e3fd704a238e176afee162058a":{
      "scriptId":"u2"},
    "4b4ea81b536240fe8b2d00c3a3056356":{
      "scriptId":"u3"},
    "54c2b528f7964e81ad4408661ee733b8":{
      "scriptId":"u4"},
    "73a9c08306724c65b5dd70757c092b6f":{
      "scriptId":"u5"},
    "30941627256d4b938d39def48a4f960f":{
      "scriptId":"u6"}}});