$axure.loadCurrentPage({
  "url":"添加设备.html",
  "generationDate":new Date(1450147155420.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4491c2fdf7c247dbae87f7f84267a9f5",
    "type":"Axure:Page",
    "name":"添加设备",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3e582e64eeda4e09a1142959d01b17c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"729923f640f645ca94aea3530c3de9d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"581aae7a6ad74296a2d6e05fd8e3357c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":112},
            "size":{
              "width":370,
              "height":658}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bc7ad2012e449d18a0c7325f8bd162d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":112},
                "size":{
                  "width":370,
                  "height":658}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加设备/u2.jpg"}},
{
          "id":"8577abfd83b543c3822c8b2b9b78420e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "3e582e64eeda4e09a1142959d01b17c3":{
      "scriptId":"u0"},
    "729923f640f645ca94aea3530c3de9d2":{
      "scriptId":"u1"},
    "581aae7a6ad74296a2d6e05fd8e3357c":{
      "scriptId":"u2"},
    "3bc7ad2012e449d18a0c7325f8bd162d":{
      "scriptId":"u3"},
    "8577abfd83b543c3822c8b2b9b78420e":{
      "scriptId":"u4"}}});