$axure.loadCurrentPage({
  "url":"场景信息.html",
  "generationDate":new Date(1450147155256.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3d8c4e8f85844b93bbbe36ab3d4d533e",
    "type":"Axure:Page",
    "name":"场景信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16c29dc7d9bb44ae832ddc5f598c6138",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d703930ab6044b4914292f6d65af3e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"f20495f33c744d4c96c865e74b1150ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":370,
              "height":658}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4481eb80f1d4401a4a645b882424b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":370,
                  "height":658}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/场景信息/u2.jpg"}},
{
          "id":"6c53eea9cecb48b3a6e061648c51b546",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "16c29dc7d9bb44ae832ddc5f598c6138":{
      "scriptId":"u0"},
    "6d703930ab6044b4914292f6d65af3e3":{
      "scriptId":"u1"},
    "f20495f33c744d4c96c865e74b1150ab":{
      "scriptId":"u2"},
    "b4481eb80f1d4401a4a645b882424b37":{
      "scriptId":"u3"},
    "6c53eea9cecb48b3a6e061648c51b546":{
      "scriptId":"u4"}}});