$axure.loadCurrentPage({
  "url":"帮助说明.html",
  "generationDate":new Date(1450147155754.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5767e1832a4e477286dc3954534fc339",
    "type":"Axure:Page",
    "name":"帮助说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4dfe777a06b34c8da6429a253858c461",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f22341c08241fb9e3c5099d98e3d0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"1fec178f972048b6a9b67a3dd66d2b82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":370,
              "height":658}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4f4f88973640e885c7c9c93ea9ae45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":370,
                  "height":658}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助说明/u2.jpg"}},
{
          "id":"c8411dc4225e4914af735ae4a0433145",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4dfe777a06b34c8da6429a253858c461":{
      "scriptId":"u0"},
    "55f22341c08241fb9e3c5099d98e3d0e":{
      "scriptId":"u1"},
    "1fec178f972048b6a9b67a3dd66d2b82":{
      "scriptId":"u2"},
    "5c4f4f88973640e885c7c9c93ea9ae45":{
      "scriptId":"u3"},
    "c8411dc4225e4914af735ae4a0433145":{
      "scriptId":"u4"}}});