$axure.loadCurrentPage({
  "url":"单孔插座更多控制.html",
  "generationDate":new Date(1450070652261.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4d1d20378de46ecb9f8680a0d90661a",
    "type":"Axure:Page",
    "name":"单孔插座更多控制",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2d665524761c44be9620fab663bc5d02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":605},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d07eb23439d449e884067160e9326a28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":605},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u0.png"}},
{
          "id":"b30d7fcf073d44658d2c21abc75df62c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":605},
            "size":{
              "width":430,
              "height":774},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45c7f4f1337429ba79b2497239a4700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":605},
                "size":{
                  "width":430,
                  "height":774},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u2.png"}},
{
          "id":"b19a3f40eb444045807aa5f3b6dc73d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1379},
            "size":{
              "width":430,
              "height":183},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb0539306ac4b23b2786784adde8748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1379},
                "size":{
                  "width":430,
                  "height":183},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u4.png"}},
{
          "id":"c6eb90d5c8ba4996b0a28358102d857d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":106},
            "size":{
              "width":373,
              "height":1350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a24dbc29e1346c0a2c3b2a1f57f2b3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":106},
                "size":{
                  "width":373,
                  "height":1350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单孔插座更多控制/u6.jpg"}},
{
          "id":"322b33562b934ef5a5e3534419b2b18d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb476ef08faa42db829497df717af8ed",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":790},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 多孔插座定时",
                      "target":{
                        "targetType":"page",
                        "url":"多孔插座定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a2a593ddcfcf4b40b9192a16f998c760",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":378,
              "y":802},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e0e5d494e4f4a3aae45ee5dcb2af4bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":378,
                  "y":802},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"06917e90de414fc3961385b08eec6911",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":1200},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 倒计时设置",
                      "target":{
                        "targetType":"page",
                        "url":"倒计时设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"946b7c1804b14b6586d8f210bd4ed1ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":380,
              "y":1210},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d7b1544dae4998a2c13e3408927745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":380,
                  "y":1210},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2d665524761c44be9620fab663bc5d02":{
      "scriptId":"u0"},
    "d07eb23439d449e884067160e9326a28":{
      "scriptId":"u1"},
    "b30d7fcf073d44658d2c21abc75df62c":{
      "scriptId":"u2"},
    "b45c7f4f1337429ba79b2497239a4700":{
      "scriptId":"u3"},
    "b19a3f40eb444045807aa5f3b6dc73d2":{
      "scriptId":"u4"},
    "6fb0539306ac4b23b2786784adde8748":{
      "scriptId":"u5"},
    "c6eb90d5c8ba4996b0a28358102d857d":{
      "scriptId":"u6"},
    "3a24dbc29e1346c0a2c3b2a1f57f2b3c":{
      "scriptId":"u7"},
    "322b33562b934ef5a5e3534419b2b18d":{
      "scriptId":"u8"},
    "eb476ef08faa42db829497df717af8ed":{
      "scriptId":"u9"},
    "a2a593ddcfcf4b40b9192a16f998c760":{
      "scriptId":"u10"},
    "2e0e5d494e4f4a3aae45ee5dcb2af4bf":{
      "scriptId":"u11"},
    "06917e90de414fc3961385b08eec6911":{
      "scriptId":"u12"},
    "946b7c1804b14b6586d8f210bd4ed1ad":{
      "scriptId":"u13"},
    "b5d7b1544dae4998a2c13e3408927745":{
      "scriptId":"u14"}}});