$axure.loadCurrentPage({
  "url":"设置灯组.html",
  "generationDate":new Date(1454143465850.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"569f22db5eab4a1a8694484945935ad2",
    "type":"Axure:Page",
    "name":"设置灯组",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"826297aa12ac497ea708b7f543b560b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4609bb10fcf48f2bf7d15b29ddd04ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lighting_cloud_v2/u0.png"}},
{
          "id":"69020920a5084197b2f23ddf33970fb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":29,
              "y":109},
            "size":{
              "width":372,
              "height":661}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33203a41fbd341b2821b3735ac841397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":29,
                  "y":109},
                "size":{
                  "width":372,
                  "height":661}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置灯组/u2.jpg"}},
{
          "id":"e19f0a5115ca41be8ed52246f3ca3d55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":240,
              "y":700},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be0f0d419bb49c599955b75c71f4fb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":240,
                  "y":700},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/色温_亮度/u11.png"}},
{
          "id":"fe99031119d24da3a645e43d41df0ef9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":690},
            "size":{
              "width":330,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组灯",
                      "target":{
                        "targetType":"page",
                        "url":"组灯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8741a95356d848ae91bc47928d3553c3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":136},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "826297aa12ac497ea708b7f543b560b7":{
      "scriptId":"u0"},
    "d4609bb10fcf48f2bf7d15b29ddd04ff":{
      "scriptId":"u1"},
    "69020920a5084197b2f23ddf33970fb3":{
      "scriptId":"u2"},
    "33203a41fbd341b2821b3735ac841397":{
      "scriptId":"u3"},
    "e19f0a5115ca41be8ed52246f3ca3d55":{
      "scriptId":"u4"},
    "3be0f0d419bb49c599955b75c71f4fb0":{
      "scriptId":"u5"},
    "fe99031119d24da3a645e43d41df0ef9":{
      "scriptId":"u6"},
    "8741a95356d848ae91bc47928d3553c3":{
      "scriptId":"u7"}}});