$axure.loadCurrentPage({
  "url":"设备分享.html",
  "generationDate":new Date(1450070652123.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3a1233ae4ae8464eb1cad3b66e6aedfd",
    "type":"Axure:Page",
    "name":"设备分享",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cc0ff747d6ab4a1ba5a693e882f904c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ebd1857b774869b654f783011867cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"8ec8662343f44d7cb8725c802529da5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":591},
            "size":{
              "width":430,
              "height":289},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a56cf678afa4c8793e9e5e654ab5172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":591},
                "size":{
                  "width":430,
                  "height":289},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更多设置/u2.png"}},
{
          "id":"2999bad7734e4ba3bc352b6e9f4f76e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":880},
            "size":{
              "width":430,
              "height":171},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098d259117d04d7ba5ac19cc9b008576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":880},
                "size":{
                  "width":430,
                  "height":171},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更多设置/u4.png"}},
{
          "id":"223411db8ae045e0a18ae3b613e2a1a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":374,
              "height":843}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed3927309ab4da084ec3f5a9dcf3b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":374,
                  "height":843}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设备分享/u6.jpg"}},
{
          "id":"3b7ebefef7204a5da620cd7b9126c0d8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "cc0ff747d6ab4a1ba5a693e882f904c6":{
      "scriptId":"u0"},
    "b1ebd1857b774869b654f783011867cd":{
      "scriptId":"u1"},
    "8ec8662343f44d7cb8725c802529da5d":{
      "scriptId":"u2"},
    "6a56cf678afa4c8793e9e5e654ab5172":{
      "scriptId":"u3"},
    "2999bad7734e4ba3bc352b6e9f4f76e4":{
      "scriptId":"u4"},
    "098d259117d04d7ba5ac19cc9b008576":{
      "scriptId":"u5"},
    "223411db8ae045e0a18ae3b613e2a1a4":{
      "scriptId":"u6"},
    "eed3927309ab4da084ec3f5a9dcf3b70":{
      "scriptId":"u7"},
    "3b7ebefef7204a5da620cd7b9126c0d8":{
      "scriptId":"u8"}}});