$axure.loadCurrentPage({
  "url":"插座编辑.html",
  "generationDate":new Date(1450070652214.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7bbfe1e976954dbb80c19573c37f64b6",
    "type":"Axure:Page",
    "name":"插座编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f89c1955b77446f2bfb6375bc1530739",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"784af5baeb5a44c59ea021ff27cae2de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"3cfac31c3a2648bb939dac934bf4ab05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":374,
              "height":666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d6e53730b184963aca0c7b851fb84bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":374,
                  "height":666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑设置/u2.jpg"}},
{
          "id":"a188bb8d218b4ddc8dcf0cfdfd8d7d28",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e85057b2c1a34df5974ded74ebe6c9e0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":680},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设备（在线&amp;离线）",
                      "target":{
                        "targetType":"page",
                        "url":"我的设备（在线_离线）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3d54d8686d1040668ee16609f9d2348a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":680},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设备（在线&amp;离线）",
                      "target":{
                        "targetType":"page",
                        "url":"我的设备（在线_离线）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3e4d2e0643b24d059bc914445da2fad9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":180,
              "y":690},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3290287f01b64f5595fc74a5014ba85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":180,
                  "y":690},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"dfffe6786ce747b8b8e32f696ae0d969",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":340,
              "y":690},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b75ae98636454990a013196fba803eca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":340,
                  "y":690},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f89c1955b77446f2bfb6375bc1530739":{
      "scriptId":"u0"},
    "784af5baeb5a44c59ea021ff27cae2de":{
      "scriptId":"u1"},
    "3cfac31c3a2648bb939dac934bf4ab05":{
      "scriptId":"u2"},
    "7d6e53730b184963aca0c7b851fb84bc":{
      "scriptId":"u3"},
    "a188bb8d218b4ddc8dcf0cfdfd8d7d28":{
      "scriptId":"u4"},
    "e85057b2c1a34df5974ded74ebe6c9e0":{
      "scriptId":"u5"},
    "3d54d8686d1040668ee16609f9d2348a":{
      "scriptId":"u6"},
    "3e4d2e0643b24d059bc914445da2fad9":{
      "scriptId":"u7"},
    "3290287f01b64f5595fc74a5014ba85c":{
      "scriptId":"u8"},
    "dfffe6786ce747b8b8e32f696ae0d969":{
      "scriptId":"u9"},
    "b75ae98636454990a013196fba803eca":{
      "scriptId":"u10"}}});