$axure.loadCurrentPage({
  "url":"定时编辑.html",
  "generationDate":new Date(1450147154886.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"195f6a4922b24b549aabfc502a5b0c02",
    "type":"Axure:Page",
    "name":"定时编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f6c4751162b24bf89dd924d908d24ea8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"958fddedf2d7403f86e439b3c9e727d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"df7b67364545444c921f7b1d48fa1e49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":756},
            "size":{
              "width":448,
              "height":271}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d5a1352e49148afb737a081a5a3fb87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":756},
                "size":{
                  "width":448,
                  "height":271}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/白光灯/u2.png"}},
{
          "id":"a1f41ef6179a4df49275cedd1a9e83b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":110},
            "size":{
              "width":370,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba0284dff0d4c4a9a8a07b01e18cff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":110},
                "size":{
                  "width":370,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/白光灯/u4.png"}},
{
          "id":"9b5c2d53c3ef444dbba1275b2535d038",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":31,
              "y":110},
            "size":{
              "width":369,
              "height":779}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55087cdd1db44f7ea90777325b00239c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":31,
                  "y":110},
                "size":{
                  "width":369,
                  "height":779}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定时编辑/u6.jpg"}},
{
          "id":"bc387f29e2fa42e982b2f9e1dc8c4b77",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e51aa9fab9a94588a6072a1630001797",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":630},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 白光灯",
                      "target":{
                        "targetType":"page",
                        "url":"白光灯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b4da4419245647788527a6230503a52c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":685},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加定时",
                      "target":{
                        "targetType":"page",
                        "url":"添加定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3fb9d2c7842248dbb010d3ad5273a7b4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":748},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加定时",
                      "target":{
                        "targetType":"page",
                        "url":"添加定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2cddf2377aab4ab6bd5418f5ad7a6eaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":379,
              "y":647},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ace65c4b4b442878bcc881549dce357",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":379,
                  "y":647},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"538d1519b2fb4060abd055e97c224340",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":378,
              "y":694},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8af17b622d47fab61b0448d989ca94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":378,
                  "y":694},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"f1e45ce38c5749ed82f9d094a1d8fe93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":378,
              "y":760},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ca18ba7bd74209b282fe686fd3db23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":378,
                  "y":760},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f6c4751162b24bf89dd924d908d24ea8":{
      "scriptId":"u0"},
    "958fddedf2d7403f86e439b3c9e727d5":{
      "scriptId":"u1"},
    "df7b67364545444c921f7b1d48fa1e49":{
      "scriptId":"u2"},
    "2d5a1352e49148afb737a081a5a3fb87":{
      "scriptId":"u3"},
    "a1f41ef6179a4df49275cedd1a9e83b0":{
      "scriptId":"u4"},
    "6ba0284dff0d4c4a9a8a07b01e18cff0":{
      "scriptId":"u5"},
    "9b5c2d53c3ef444dbba1275b2535d038":{
      "scriptId":"u6"},
    "55087cdd1db44f7ea90777325b00239c":{
      "scriptId":"u7"},
    "bc387f29e2fa42e982b2f9e1dc8c4b77":{
      "scriptId":"u8"},
    "e51aa9fab9a94588a6072a1630001797":{
      "scriptId":"u9"},
    "b4da4419245647788527a6230503a52c":{
      "scriptId":"u10"},
    "3fb9d2c7842248dbb010d3ad5273a7b4":{
      "scriptId":"u11"},
    "2cddf2377aab4ab6bd5418f5ad7a6eaf":{
      "scriptId":"u12"},
    "4ace65c4b4b442878bcc881549dce357":{
      "scriptId":"u13"},
    "538d1519b2fb4060abd055e97c224340":{
      "scriptId":"u14"},
    "fa8af17b622d47fab61b0448d989ca94":{
      "scriptId":"u15"},
    "f1e45ce38c5749ed82f9d094a1d8fe93":{
      "scriptId":"u16"},
    "c1ca18ba7bd74209b282fe686fd3db23":{
      "scriptId":"u17"}}});