$axure.loadCurrentPage({
  "url":"白光灯.html",
  "generationDate":new Date(1450147154735.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"269a53dce0ba496b9d71ee9b4609f7da",
    "type":"Axure:Page",
    "name":"白光灯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9b36e6fed84247c984856e6b73b7e3a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0531ef542de044ffaa0d0c77629bb4fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"2e328a5f8fe34137b1824f87dc24f9bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":758},
            "size":{
              "width":448,
              "height":271}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aab3079ece9f4ec2acb9fb122a9207c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":758},
                "size":{
                  "width":448,
                  "height":271}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/白光灯/u2.png"}},
{
          "id":"9d717f02c8c448a189196ea7734994b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":110},
            "size":{
              "width":370,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bec6901216f4e64bd9acb118168513f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":110},
                "size":{
                  "width":370,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/白光灯/u4.png"}},
{
          "id":"2c2c78aa46294d4f837e9c56791ac391",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":110},
            "size":{
              "width":370,
              "height":780}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b18bb9748674212904bc13e560178a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":110},
                "size":{
                  "width":370,
                  "height":780}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/白光灯/u6.jpg"}},
{
          "id":"fd7eb730f332449cb8fcdf4bb5f196bf",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":132},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8364e1272162466d9924c8212fe7a8a5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":636},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 定时编辑",
                      "target":{
                        "targetType":"page",
                        "url":"定时编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8dfa9b3e3bda4fcaad82e3bf71dbb6d9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":810},
            "size":{
              "width":331,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加定时",
                      "target":{
                        "targetType":"page",
                        "url":"添加定时.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"de01a08e15874aacb5d521fbf4cd3df8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":380,
              "y":650},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f04ba45acfe4482a2eae4337614eea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":380,
                  "y":650},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"d78e4b5faac84b5db65940352c982106",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":170,
              "y":822},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5fbebff3db7444998c5c4f71210b6bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":170,
                  "y":822},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}},
{
          "id":"e2454e8c030c49ff81b44a5b88cdad7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":389,
              "y":171},
            "size":{
              "width":150,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94be827fc0ba415fb03eed4fae6e7028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":389,
                  "y":171},
                "size":{
                  "width":150,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u13.png"}},
{
          "id":"a431acede00747c68cbc91bce3f97b0d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":192},
            "size":{
              "width":99,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1,<br>(Image),<br>隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["fd4a2810df904fad8fe7a4c40ebe04f3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["02c43ef2afee4d95bcbb890df9a9a73e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b6f03f5569d64125b18c4e9709f69f1b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"02c43ef2afee4d95bcbb890df9a9a73e",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":610,
              "y":86},
            "size":{
              "width":254,
              "height":328},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0696ea8ba07e42e8982b6a7e9011712b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":610,
                  "y":86},
                "size":{
                  "width":254,
                  "height":328},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/1_u16.png"}},
{
          "id":"fd4a2810df904fad8fe7a4c40ebe04f3",
          "label":"2",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":610,
              "y":92},
            "size":{
              "width":254,
              "height":328}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"615ecd6c990a4ad68db017ddc8b45d4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":610,
                  "y":92},
                "size":{
                  "width":254,
                  "height":328}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/2_u18.png"}},
{
          "id":"b6f03f5569d64125b18c4e9709f69f1b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":290,
              "y":206},
            "size":{
              "width":89,
              "height":27},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65b373690edf4e17bc549d4f46471350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":290,
                  "y":206},
                "size":{
                  "width":89,
                  "height":27},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2,<br>隐藏 (Image),<br>1",
                      "objectsToFades":[{
                          "objectPath":["b6f03f5569d64125b18c4e9709f69f1b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["02c43ef2afee4d95bcbb890df9a9a73e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fd4a2810df904fad8fe7a4c40ebe04f3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/白光灯/u22.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "9b36e6fed84247c984856e6b73b7e3a0":{
      "scriptId":"u0"},
    "0531ef542de044ffaa0d0c77629bb4fa":{
      "scriptId":"u1"},
    "2e328a5f8fe34137b1824f87dc24f9bd":{
      "scriptId":"u2"},
    "aab3079ece9f4ec2acb9fb122a9207c0":{
      "scriptId":"u3"},
    "9d717f02c8c448a189196ea7734994b4":{
      "scriptId":"u4"},
    "5bec6901216f4e64bd9acb118168513f":{
      "scriptId":"u5"},
    "2c2c78aa46294d4f837e9c56791ac391":{
      "scriptId":"u6"},
    "9b18bb9748674212904bc13e560178a9":{
      "scriptId":"u7"},
    "fd7eb730f332449cb8fcdf4bb5f196bf":{
      "scriptId":"u8"},
    "8364e1272162466d9924c8212fe7a8a5":{
      "scriptId":"u9"},
    "8dfa9b3e3bda4fcaad82e3bf71dbb6d9":{
      "scriptId":"u10"},
    "de01a08e15874aacb5d521fbf4cd3df8":{
      "scriptId":"u11"},
    "0f04ba45acfe4482a2eae4337614eea4":{
      "scriptId":"u12"},
    "d78e4b5faac84b5db65940352c982106":{
      "scriptId":"u13"},
    "a5fbebff3db7444998c5c4f71210b6bd":{
      "scriptId":"u14"},
    "e2454e8c030c49ff81b44a5b88cdad7e":{
      "scriptId":"u15"},
    "94be827fc0ba415fb03eed4fae6e7028":{
      "scriptId":"u16"},
    "a431acede00747c68cbc91bce3f97b0d":{
      "scriptId":"u17"},
    "02c43ef2afee4d95bcbb890df9a9a73e":{
      "scriptId":"u18"},
    "0696ea8ba07e42e8982b6a7e9011712b":{
      "scriptId":"u19"},
    "fd4a2810df904fad8fe7a4c40ebe04f3":{
      "scriptId":"u20"},
    "615ecd6c990a4ad68db017ddc8b45d4d":{
      "scriptId":"u21"},
    "b6f03f5569d64125b18c4e9709f69f1b":{
      "scriptId":"u22"},
    "65b373690edf4e17bc549d4f46471350":{
      "scriptId":"u23"}}});