$axure.loadCurrentPage({
  "url":"rgb_w_日光.html",
  "generationDate":new Date(1450147155041.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"80f4ad22475940bab8aad492078d6243",
    "type":"Axure:Page",
    "name":"RGB+W_日光",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f80af55ae654f12b3926dbf81f27e7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":997}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5ade6ce090a4c27ac903f24e183662e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":997}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lightingyun-app/u0.png"}},
{
          "id":"483d8997689243f39ab559e1cf4e0591",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":2,
              "y":742},
            "size":{
              "width":431,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381c64a903544c4283bf51551c167b63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":2,
                  "y":742},
                "size":{
                  "width":431,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/rgb_w_彩光/u2.png"}},
{
          "id":"808f74b95f63456c909ecd4a2bc6b67a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":122},
            "size":{
              "width":370,
              "height":822}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fc62e4b46a24ae6b82378ee16ddb235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":122},
                "size":{
                  "width":370,
                  "height":822}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/rgb_w_日光/u4.jpg"}},
{
          "id":"998650d5f96343158d3a6831cc330f1d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":143},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6381e3961a2948b2b0b883d62428f910",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":420},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 RGB+W_彩光",
                      "target":{
                        "targetType":"page",
                        "url":"rgb_w_彩光.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5ed3d08fcd234f278a57963ac978c795",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":111,
              "y":429},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219ca39da87f4507b5fc211c92a0fced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":111,
                  "y":429},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/灯具/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2f80af55ae654f12b3926dbf81f27e7e":{
      "scriptId":"u0"},
    "e5ade6ce090a4c27ac903f24e183662e":{
      "scriptId":"u1"},
    "483d8997689243f39ab559e1cf4e0591":{
      "scriptId":"u2"},
    "381c64a903544c4283bf51551c167b63":{
      "scriptId":"u3"},
    "808f74b95f63456c909ecd4a2bc6b67a":{
      "scriptId":"u4"},
    "8fc62e4b46a24ae6b82378ee16ddb235":{
      "scriptId":"u5"},
    "998650d5f96343158d3a6831cc330f1d":{
      "scriptId":"u6"},
    "6381e3961a2948b2b0b883d62428f910":{
      "scriptId":"u7"},
    "5ed3d08fcd234f278a57963ac978c795":{
      "scriptId":"u8"},
    "219ca39da87f4507b5fc211c92a0fced":{
      "scriptId":"u9"}}});