$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1454143465891.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3a8aa804bc284323ac8419839f7848d1",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"719ae8382335424b95c2fef7bb540712",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e122e6ebfa9467290d2cf6a5f1be279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lighting_cloud_v2/u0.png"}},
{
          "id":"8be4db50aeab4d91a6efa63ee1b2976a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":28,
              "y":110},
            "size":{
              "width":372,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf395ddcb4174e88a967d72adf4fd96f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":28,
                  "y":110},
                "size":{
                  "width":372,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u2.png"}},
{
          "id":"b3a11fd83a2848ada41393ce03a2c393",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":690},
            "size":{
              "width":330,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 色温+亮度",
                      "target":{
                        "targetType":"page",
                        "url":"色温_亮度.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"03cb76cb437f42c38239988338295467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":237,
              "y":700},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ffb14c9fd794f39bd88919e1d6256c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":237,
                  "y":700},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/色温_亮度/u11.png"}},
{
          "id":"07d583bc768540708f567d4a1d344a7d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":136},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "719ae8382335424b95c2fef7bb540712":{
      "scriptId":"u0"},
    "6e122e6ebfa9467290d2cf6a5f1be279":{
      "scriptId":"u1"},
    "8be4db50aeab4d91a6efa63ee1b2976a":{
      "scriptId":"u2"},
    "cf395ddcb4174e88a967d72adf4fd96f":{
      "scriptId":"u3"},
    "b3a11fd83a2848ada41393ce03a2c393":{
      "scriptId":"u4"},
    "03cb76cb437f42c38239988338295467":{
      "scriptId":"u5"},
    "2ffb14c9fd794f39bd88919e1d6256c2":{
      "scriptId":"u6"},
    "07d583bc768540708f567d4a1d344a7d":{
      "scriptId":"u7"}}});