$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1450147132660.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d404d2e1eca3415caf85c83a9ec1db9b",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0900afd788a64590896243e2096b4cdc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d18eaddaaa9d498bb68473952a3b2359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"c2ad7f193ef14245be33da1ab2bc1ed2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":371,
              "height":659}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73574a2f4c7e498d96dc65667a73a7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":371,
                  "height":659}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 灯具",
                      "target":{
                        "targetType":"page",
                        "url":"灯具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "0900afd788a64590896243e2096b4cdc":{
      "scriptId":"u0"},
    "d18eaddaaa9d498bb68473952a3b2359":{
      "scriptId":"u1"},
    "c2ad7f193ef14245be33da1ab2bc1ed2":{
      "scriptId":"u2"},
    "73574a2f4c7e498d96dc65667a73a7eb":{
      "scriptId":"u3"}}});